export enum ActionType {
  Always = 'Always',
  OnPicked = 'OnPicked',
  OnUse = 'OnUse',
  OnSecondaryUse = 'OnSecondaryUse',
  OnWearing = 'OnWearing',
  OnContaining = 'OnContaining',
  OnContained = 'OnContained',
  OnNotContained = 'OnNotContained',
  OnActive = 'OnActive',
  OnFailure = 'OnFailure',
  OnBroken = 'OnBroken',
  OnFire = 'OnFire',
  InWater = 'InWater',
  NotInWater = 'NotInWater',
  OnImpact = 'OnImpact',
  OnEating = 'OnEating',
  OnDamaged = 'OnDamaged',
  OnSevered = 'OnSevered',
  OnProduceSpawned = 'OnProduceSpawned',
  OnOpen = 'OnOpen',
  OnClose = 'OnClose',
  OnSpawn = 'OnSpawn',
  OnSuccess = 'OnSuccess',
  OnAbility = 'OnAbility',
  OnDeath = 'OnBroken',
}
