export enum AfflictionType {
  InternalDamage = 'internaldamage',
  BluntForceTrauma = 'blunttrauma',
  Lacerations = 'lacerations',
  BiteWounds = 'bitewounds',
  GunshotWound = 'gunshotwound',
  OrganDamage = 'organdamage',
  DeepTissueInjury = 'deeptissueinjury',
  Bleeding = 'bleeding',
  Burn = 'burn',
  Bloodloss = 'bloodloss',
  Stun = 'stun',
  ProgressiveStun = 'progressivestun',
  OxygenLow = 'oxygenlow',
  HuskInfection = 'huskinfection',
  Paralysis = 'paralysis',
  MorbusinePoisoning = 'morbusinepoisoning',
  SufforinPoisoning = 'sufforinpoisoning',
  DeliriuminePoisoning = 'deliriuminepoisoning',
  CyanidePoisoning = 'cyanidepoisoning',
  RadiationSickness = 'radiationsickness',
  Psychosis = 'psychosis',
  Drunk = 'drunk',
  Nausea = 'nausea',
  Hallucinating = 'hallucinating',
}
