import { DeconstructItem } from '@interfaces/deconstruct-item';
import { FabricationRecipe } from '@interfaces/fabrication-recipe';
import { Holdable } from '@interfaces/holdable';
import { ItemComponent } from '@interfaces/item-component';
import { ItemContainer } from '@interfaces/item-container';
import { MeleeWeapon } from '@interfaces/melee-weapon';
import { PriceInfo } from '@interfaces/price-info';
import { Projectile } from '@interfaces/projectile';
import { RangedWeapon } from '@interfaces/ranged-weapon';
import { SpriteImage } from '@interfaces/sprite';
import { Throwable } from '@interfaces/throwable';

export interface ItemPrefab {
  identifier: string;
  nameIdentifier?: string;
  descriptionIdentifier?: string;
  name?: string;
  englishName?: string;
  description?: string;
  modName?: string;
  variantOf?: string;
  category: string;
  tags?: string[];
  price?: PriceInfo;
  fabricationRecipes?: FabricationRecipe[];
  deconstructTime?: number;
  deconstructItems?: DeconstructItem[];
  maxStackSize?: number;
  sprite?: SpriteImage;
  infectedIcon?: SpriteImage;
  containedSprites?: SpriteImage[];
  decorativeSprite?: SpriteImage[];
  itemContainer?: ItemContainer;
  component?: ItemComponent;
  meleeWeapon?: MeleeWeapon;
  rangedWeapon?: RangedWeapon;
  projectile?: Projectile;
  holdable?: Holdable;
  throwable?: Throwable;
}
